### ISSUE TITLE
Set up Continuous Integration/Delivery with CircleCI and Docker Hub

### ISSUE THREAD

**Issue by krisnova** [kubicorn/controller#6]
Can we set up travis for this repo just like we have for the main repo? 

Also can we configure Travis to do a docker build/push on every merge into master?

**Comment by xmudrii** [comment]
Should we use CircleCI for this repo as well, as we use it for the main repo, or TravisCI would be good enough?

**Comment by krisnova** [comment]
we should keep everything the same :) lets use circleci
